spring:
  application:
    name: pedidos
  datasource:
    url: jdbc:postgresql://localhost:5555/ecommercepedidos
    username: example
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ecommerce-atualizacao-pedido
      auto-offset-reset: earliest

server:
  port: 8080

ecommerce:
  pedidos:
    clients:
      produtos:
        url: "http://localhost:8081/produtos"
      clientes:
        url: "http://localhost:8082/clientes"
  config:
    kafka:
      server-url: 'http://localhost:29092'
      topics:
        pedidos-pagos: 'ecommerce.pedidos-pagos'
        pedidos-faturados: 'ecommerce.pedidos-faturados'
        pedidos-enviados: 'ecommerce.pedidos-enviados'