spring:
  application:
    name: faturamento
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ecommerce-faturamento
      auto-offset-reset: earliest

ecommerce:
  config:
    kafka:
      topics:
        pedidos-pagos: 'ecommerce.pedidos-pagos'
        pedidos-faturados: 'ecommerce.pedidos-faturados'

server:
  port: 8083

minio:
  url: 'http:localhost:9000'
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: ecommerce.faturas
