version: '3.9'

services:
  db:
    image: postgres:17.4
    container_name: db_ecommerce
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_MULTIPLE_DATABASES: ecommerceprodutos, ecommercepedidos, ecommerceclientes
    ports:
      - "5555:5432"
    volumes:
      - ./data:/var/lib/postgresql/data